spring.application.name=priceseer

spring.kafka.bootstrap-servers=192.168.8.244:9092
spring.kafka.consumer.group-id=priceseer-consumer
spring.kafka.consumer.auto-offset-reset=latest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer

spring.datasource.url=jdbc:postgresql://localhost:15432/priceseer
spring.datasource.username=priceseer
spring.datasource.password=priceseer
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

app.team-name=BAAM
app.history-size=120
